### ISSUE TITLE
Missing Button

### ISSUE THREAD

**Issue by machida23** [millers23/Citadels#5]
There needs to be a button to discard a card since every time you draw two cards, you need to get rid of one of them. The Use Case Diagram shows that you draw two cards per turn, but the method that draws a card only returns a single card.

**Comment by millers23** [comment]
That's something we can fix pretty quickly. We had an idea that if your character's ability was to draw more cards you could press the draw card button, which would mean it should only draw one (due to how the ability works) and be pressed multiple times. We moved that mapping to the ability button but haven't fixed that yet.
